### ISSUE TITLE
Error: Could not parse application options: invalid option: --manifestdir

### ISSUE THREAD

**Issue by mintao** [mayflower/wasted#76]
- I have the latest Box ('puppetlabs/ubuntu-14.04-64-puppet)
- I have the latest stable Vagrant (1.7.4)
- and - that will impress you the most - I have no clue.

After calling `vagrant provision` I got this error: *Error: Could not parse application options: invalid option: --manifestdir*

After several minutes of googling [this](https://stackoverflow.com/questions/31811458/error-could-not-parse-application-options-invalid-option-manifestdir) brought the solution (at least for me).

 We may have to include it!?

 config.vm.provision "shell", inline: <<-SHELL
    if [ ! -f /deb-get ]; then wget https://apt.puppetlabs.com/puppetlabs-release-trusty.deb  && sudo touch /deb-get; fi
    if [ ! -f /deb-run ]; then sudo dpkg -i puppetlabs-release-trusty.deb  && sudo touch /deb-run; fi
    if [ ! -f /apt-get-run ]; then sudo apt-get update && sudo touch /apt-get-run; fi
    if [ ! -f /apt-get-puppet ]; then sudo apt-get install --yes --force-yes puppet && sudo touch /apt-get-puppet; fi
  SHELL

**Comment by fpletz** [comment]
Why are you using the puppetlabs basebox instead of ours? This is untested and we already install puppet from the puppetlabs repo when building our basebox.

**Comment by codec** [comment]
We don't support other boxes (for now). Sorry.

**Comment by globin** [comment]
Specifically we don't support puppet 4 which is the issue here
