### ISSUE TITLE
Use of hard-coded default password and use of HTTP

### ISSUE THREAD

**Issue by akondasif** [mayflower/wasted#86]
I am a security researcher, who is looking for security smells in Puppet scripts. 
I noticed instances of hard-coded passwords, which are against the best practices 
recommended by Common Weakness Enumeration (CWE) [https://cwe.mitre.org/data/definitions/259.html] and also by other security practitioners. Feedback is welcome. 

Pull request: https://github.com/mayflower/wasted/pull/85

Here is where I noticed hard-coded passwords: 
https://github.com/mayflower/wasted/blob/master/site/component/manifests/postgresql.pp

**Comment by akondasif** [comment]
Greetings,

I am a security researcher, who is looking for security smells in Puppet scripts. I found instances where the HTTP protocol is used instead of HTTPS (HTTP with TLS). According to the Common Weakness Enumeration organization this is a security weakness (https://cwe.mitre.org/data/definitions/319.html).  I was wondering why HTTP is used? Is it because of lack of tool support?

I am trying to find out if developers are forced to adopt bad practices due to lack of tool support when it comes to the HTTPS protocol. Maybe it is due to dependency on a resource that uses HTTP?    

Any feedback is appreciated.  


Source: https://github.com/mayflower/wasted/blob/master/site/component/manifests/standalone_app.pp

**Comment by mmoll** [comment]
this is fine.
